name: Build and publish app release

on:
  release:
    types: [published]

env:
  APP_NAME: ${{ github.repository_owner }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@v2
        with:
          require: admin

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v1.1
        id: versions
        with:
          path: ${{ env.APP_NAME }}
          fallbackNode: '^12'
          fallbackNpm: '^6'

      - name: Get appinfo data
        id: appinfo
        uses: QwerMike/xpath-action@v1
        with:
          filename: ${{ env.APP_NAME }}/appinfo/info.xml
          expression: '//info//dependencies//nextcloud/string(@min-version)'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Build
        run: |
          cd ${{ env.APP_NAME }}
          npm ci
          npm run build
          krankerl package || make appstore

      - name: Checkout server
        run: |
          wget --quiet https://download.nextcloud.com/server/releases/latest-${{ steps.appinfo.outputs.result }}.zip
          unzip latest-${{ steps.appinfo.outputs.result }}.zip

      - name: Sign app
        run: |
          # Extracting release
          cd ${{ env.APP_NAME }}/build/artifacts
          tar -xvf ${{ env.APP_NAME }}.tar.gz
          cd ../../../
          # Setting up keys
          echo "${{ secrets.APP_PRIVATE_KEY }}" > ${{ env.APP_NAME }}.key
          wget --quiet "https://github.com/nextcloud/app-certificate-requests/raw/master/${{ env.APP_NAME }}/${{ env.APP_NAME }}.crt"
          # Signing
          php nextcloud/occ integrity:sign-app --privateKey=../${{ env.APP_NAME }}.key --certificate=../${{ env.APP_NAME }}.crt --path=../${{ env.APP_NAME }}/build/artifacts/${{ env.APP_NAME }}
          # Rebuilding archive
          cd ${{ env.APP_NAME }}/build/artifacts
          tar -zcvf ${{ env.APP_NAME }}.tar.gz ${{ env.APP_NAME }}

      - name: Attach tarball to github release
        uses: svenstaro/upload-release-action@v2
        id: attach_to_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.APP_NAME }}/build/artifacts/${{ env.APP_NAME }}.tar.gz
          asset_name: ${{ env.APP_NAME }}-${{ github.ref }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      # - name: Upload app to Nextcloud appstore
      #   uses: R0Wi/nextcloud-appstore-push-action@v1
      #   with:
      #     app_name: ${{ env.APP_NAME }}
      #     appstore_token: ${{ secrets.APPSTORE_TOKEN }}
      #     download_url: ${{ steps.attach_to_release.outputs.browser_download_url }}
      #     app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      #     nightly: ${{ github.event.release.prerelease }}

